g++ -c -fvisibility-inlines-hidden -DCASE_INSENSITIVE -fpascal-strings -isysroot/Developer/SDKs/MacOSX10.5.sdk -arch i386 -DCASE_INSENSITIVE -F/Users/ateague/QT/lib -DQT_NO_STL -DQT_THREAD_SUPPORT -DQT_NO_CAST_TO_ASCII -DQT_NO_CAST_FROM_ASCII -DQT_STATICPLUGIN -DQT_NO_DEBUG -DQT_NO_CHECK -O2 -UQT_NO_CAST_FROM_ASCII -DOS_MACOSX -DOS_MACOSX105 -DOS_MACOSXX86 -DOS_MACOSX105X86 -I. -I/Users/ateague/QT/include/Qt -I/Users/ateague/QT/lib/Qt.framework/Headers -I/Users/ateague/QT/include/QtCore -I/Users/ateague/QT/lib/QtCore.framework/Headers -I/Users/ateague/QT/include/QtGui -I/Users/ateague/QT/lib/QtGui.framework/Headers -I/Users/ateague/QT/include/QtAssistant -I/Users/ateague/QT/lib/QtAssistant.framework/Headers -I/Users/ateague/QT/include/QtNetwork -I/Users/ateague/QT/lib/QtNetwork.framework/Headers -I/Users/ateague/QT/include/QtXml -I/Users/ateague/QT/lib/QtXml.framework/Headers -I/Users/ateague/QT/include/QtOpenGL -I/Users/ateague/QT/lib/QtOpenGL.framework/Headers -I/Users/ateague/QT/include AttrEdit.cc

g++ -c -fvisibility-inlines-hidden -DCASE_INSENSITIVE -fpascal-strings -isysroot/Developer/SDKs/MacOSX10.5.sdk -arch i386 -DCASE_INSENSITIVE -F/Users/ateague/QT/lib -DQT_NO_STL -DQT_THREAD_SUPPORT -DQT_NO_CAST_TO_ASCII -DQT_NO_CAST_FROM_ASCII -DQT_STATICPLUGIN -DQT_NO_DEBUG -DQT_NO_CHECK -O2 -UQT_NO_CAST_FROM_ASCII -DOS_MACOSX -DOS_MACOSX105 -DOS_MACOSXX86 -DOS_MACOSX105X86 -I. -I/Users/ateague/QT/include/Qt -I/Users/ateague/QT/lib/Qt.framework/Headers -I/Users/ateague/QT/include/QtCore -I/Users/ateague/QT/lib/QtCore.framework/Headers -I/Users/ateague/QT/include/QtGui -I/Users/ateague/QT/lib/QtGui.framework/Headers -I/Users/ateague/QT/include/QtAssistant -I/Users/ateague/QT/lib/QtAssistant.framework/Headers -I/Users/ateague/QT/include/QtNetwork -I/Users/ateague/QT/lib/QtNetwork.framework/Headers -I/Users/ateague/QT/include/QtXml -I/Users/ateague/QT/lib/QtXml.framework/Headers -I/Users/ateague/QT/include/QtOpenGL -I/Users/ateague/QT/lib/QtOpenGL.framework/Headers -I/Users/ateague/QT/include MainDialog.cc

g++ -c -fvisibility-inlines-hidden -DCASE_INSENSITIVE -fpascal-strings -isysroot/Developer/SDKs/MacOSX10.5.sdk -arch i386 -DCASE_INSENSITIVE -F/Users/ateague/QT/lib -DQT_NO_STL -DQT_THREAD_SUPPORT -DQT_NO_CAST_TO_ASCII -DQT_NO_CAST_FROM_ASCII -DQT_STATICPLUGIN -DQT_NO_DEBUG -DQT_NO_CHECK -O2 -UQT_NO_CAST_FROM_ASCII -DOS_MACOSX -DOS_MACOSX105 -DOS_MACOSXX86 -DOS_MACOSX105X86 -I. -I/Users/ateague/QT/include/Qt -I/Users/ateague/QT/lib/Qt.framework/Headers -I/Users/ateague/QT/include/QtCore -I/Users/ateague/QT/lib/QtCore.framework/Headers -I/Users/ateague/QT/include/QtGui -I/Users/ateague/QT/lib/QtGui.framework/Headers -I/Users/ateague/QT/include/QtAssistant -I/Users/ateague/QT/lib/QtAssistant.framework/Headers -I/Users/ateague/QT/include/QtNetwork -I/Users/ateague/QT/lib/QtNetwork.framework/Headers -I/Users/ateague/QT/include/QtXml -I/Users/ateague/QT/lib/QtXml.framework/Headers -I/Users/ateague/QT/include/QtOpenGL -I/Users/ateague/QT/lib/QtOpenGL.framework/Headers -I/Users/ateague/QT/include dtgconfig.cc

/Users/ateague/QT/bin/moc AttrEdit.h -o mAttrEdit.cpp
g++ -c -fvisibility-inlines-hidden -DCASE_INSENSITIVE -fpascal-strings -isysroot/Developer/SDKs/MacOSX10.5.sdk -arch i386 -DCASE_INSENSITIVE -F/Users/ateague/QT/lib -DQT_NO_STL -DQT_THREAD_SUPPORT -DQT_NO_CAST_TO_ASCII -DQT_NO_CAST_FROM_ASCII -DQT_STATICPLUGIN -DQT_NO_DEBUG -DQT_NO_CHECK -O2 -UQT_NO_CAST_FROM_ASCII -DOS_MACOSX -DOS_MACOSX105 -DOS_MACOSXX86 -DOS_MACOSX105X86 -I. -I/Users/ateague/QT/include/Qt -I/Users/ateague/QT/lib/Qt.framework/Headers -I/Users/ateague/QT/include/QtCore -I/Users/ateague/QT/lib/QtCore.framework/Headers -I/Users/ateague/QT/include/QtGui -I/Users/ateague/QT/lib/QtGui.framework/Headers -I/Users/ateague/QT/include/QtAssistant -I/Users/ateague/QT/lib/QtAssistant.framework/Headers -I/Users/ateague/QT/include/QtNetwork -I/Users/ateague/QT/lib/QtNetwork.framework/Headers -I/Users/ateague/QT/include/QtXml -I/Users/ateague/QT/lib/QtXml.framework/Headers -I/Users/ateague/QT/include/QtOpenGL -I/Users/ateague/QT/lib/QtOpenGL.framework/Headers -I/Users/ateague/QT/include mAttrEdit.cpp

/Users/ateague/QT/bin/moc MainDialog.h -o mMainDialog.cpp
g++ -c -fvisibility-inlines-hidden -DCASE_INSENSITIVE -fpascal-strings -isysroot/Developer/SDKs/MacOSX10.5.sdk -arch i386 -DCASE_INSENSITIVE -F/Users/ateague/QT/lib -DQT_NO_STL -DQT_THREAD_SUPPORT -DQT_NO_CAST_TO_ASCII -DQT_NO_CAST_FROM_ASCII -DQT_STATICPLUGIN -DQT_NO_DEBUG -DQT_NO_CHECK -O2 -UQT_NO_CAST_FROM_ASCII -DOS_MACOSX -DOS_MACOSX105 -DOS_MACOSXX86 -DOS_MACOSX105X86 -I. -I/Users/ateague/QT/include/Qt -I/Users/ateague/QT/lib/Qt.framework/Headers -I/Users/ateague/QT/include/QtCore -I/Users/ateague/QT/lib/QtCore.framework/Headers -I/Users/ateague/QT/include/QtGui -I/Users/ateague/QT/lib/QtGui.framework/Headers -I/Users/ateague/QT/include/QtAssistant -I/Users/ateague/QT/lib/QtAssistant.framework/Headers -I/Users/ateague/QT/include/QtNetwork -I/Users/ateague/QT/lib/QtNetwork.framework/Headers -I/Users/ateague/QT/include/QtXml -I/Users/ateague/QT/lib/QtXml.framework/Headers -I/Users/ateague/QT/include/QtOpenGL -I/Users/ateague/QT/lib/QtOpenGL.framework/Headers -I/Users/ateague/QT/include mMainDialog.cpp

g++ -Wl,-syslibroot,/Developer/SDKs/MacOSX10.5.sdk -arch i386 -ldl -Wl,-syslibroot,/Developer/SDKs/MacOSX10.5.sdk -arch i386 -L/Users/ateague/QT/lib -F/Users/ateague/QT/lib -lz -o p4dtg-config.app/Contents/MacOS/p4dtg-config  dtgconfig.o AttrEdit.o MainDialog.o -framework Carbon -framework QuickTime -framework OpenGL -framework AGL -framework AppKit -lQtOpenGL -lQtAssistantClient -lQtXml -lQtNetwork -lQtGui -lQtCore -liconv -lssl -lcrypto 
